import { responsiveFontSize } from "react-native-responsive-dimensions";
export const colorPrimary = '#8BC83F';
export const colorSecondary = '#8BC83F';
export const colorGrey = '#8391A1';
export const drawerIconSize=responsiveFontSize(23);
export const iconSize=responsiveFontSize(25);
export const grey='#727272';
export const systemGrey= '#8BC83F';
export const systemGreyBg = '#F8F9F7';
export const danger='#008F45';
export const mainColor='#008F45';
export const white='#ffff';
export const dark='#000';
export const denimBlue = '#1260CC'
export const green='green';
export const lightFont='NunitoSans-Regular';
export const regularFont='Lato-Regular';
export const mediumFont='Raleway-Regular';
export const semiBoldFont='DancingFont-SemiBold';
export const boldFont='Lato-Bold';
export const headingText=responsiveFontSize(17);
export const mainHeadingText = responsiveFontSize(30);   
export const h4=responsiveFontSize(12);
export const mediumText=responsiveFontSize(14);
export const normalText=responsiveFontSize(13);
export const samllText=responsiveFontSize(12);
export const addIcon=responsiveFontSize(45);
export const ColorGrey='rgba(0,0,0,0.3)'